// apps/invest/src/App.tsx
/** @format */

import { ArcaneAuthProvider } from '@arcane-web/arcane-auth';
import { useRoutes, Router } from 'solid-app-router';
import { Shell } from './components';
import config from './firebase.config';
import { routes } from './routes';

export function createApp() {
  const Routes = useRoutes(routes);
  return (
    <ArcaneAuthProvider config={config} name="invest">
      <Router base="invest">
        <Shell>
          <Routes />
        </Shell>
      </Router>
    </ArcaneAuthProvider>
  );
}

// apps/arcane/src/client/App.tsx
/** @format */

import { Router, useRoutes } from 'solid-app-router';
import type { VoidComponent } from 'solid-js';

const App: VoidComponent = () => {
  const Route = useRoutes([]);
  return (
    <>
      <h1>Hello</h1>
      <Route />
    </>
  );
};

export default App;

type CreateAppProps = {
  url: string;
};

export const createApp: VoidComponent<CreateAppProps> = (props) => {
  return (
    <Router url={props.url}>
      <App />
    </Router>
  );
};
