// apps/arcane/client/src/App.tsx
/** @format */

import { Router, Routes, Route } from 'solid-app-router';
import type { VoidComponent } from 'solid-js';
import { Login, Home } from './pages';

const App: VoidComponent = () => {
  return (
    <Routes>
      <Route path="/" component={Login} />
      <Route path="/home" component={Home} />
    </Routes>
  );
};

export default App;

type CreateAppProps = {
  url: string;
};

export const createApp: VoidComponent<CreateAppProps> = (props) => {
  return (
    <Router url={props.url}>
      <App />
    </Router>
  );
};

// admin/trade/src/App.tsx
/** @format */

import * as React from 'react';
import { Routes, Route } from 'react-router-dom';
import Auth from './pages/Auth';
import Home from './pages/Home';
import Users, { User, Transactions, Transaction, Group } from './pages/users';

export default function App() {
  return (
    <Routes>
      <Route path="/" element={<Home />}>
        <Route index element={<Users />} />
        <Route path=":userId">
          <Route index element={<User />} />
          <Route path="transactions">
            <Route index element={<Transactions />} />
            <Route path=":transactionId">
              <Route index element={<Transaction />} />
              <Route path=":id" element={<Group />} />
            </Route>
          </Route>
        </Route>
      </Route>

      <Route path="/auth" element={<Auth />} />
    </Routes>
  );
}
