// apps/invest/src/App.tsx
/** @format */

import { ArcaneAuthProvider } from '@arcane-web/arcane-auth';
import { useRoutes, Router } from 'solid-app-router';
import { Shell } from './components';
import config from './firebase.config';
import { routes } from './routes';

export function createApp() {
  const Routes = useRoutes(routes);
  return (
    <ArcaneAuthProvider config={config} name="invest">
      <Router base="invest">
        <Shell>
          <Routes />
        </Shell>
      </Router>
    </ArcaneAuthProvider>
  );
}

// apps/arcane/src/app.tsx
/** @format */

import type { Component, VoidComponent } from 'solid-js';
import { Router } from 'solid-app-router';
import { useRoutes } from 'solid-app-router';
import { routes } from './routes';
import '@arcane-web/alchemy';

const App: Component = () => {
  const Route = useRoutes(routes);

  return (
    <>
      <Route />
    </>
  );
};

type CreateAppProps = {
  url: string;
};

export const createApp: VoidComponent<CreateAppProps> = (props) => {
  return (
    <Router url={props.url}>
      <App />
    </Router>
  );
};
